#!/usr/bin/env bash
# This script configures Nginx for a custom 404 page

# Create a new configuration file for the custom 404 page
echo "server {
    listen 80;
    server_name _;
    error_page 404 /custom_404;
    location = /custom_404 {
        internal;
        return 404 'Ceci n\'est pas une page\n';
    }
}" > /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Reload nginx configuration
service nginx reload

