#!/usr/bin/env bash
# Fix my server with these magic 2 lines

# Check if /etc/passwd exists in /tmp, if not, copy it
if [ ! -f /tmp/passwd ]; then
    cp /etc/passwd /tmp/
fi

# Create /tmp/isworking file with content "OK"
echo OK > /tmp/isworking
